# Generated by Django 5.1.2 on 2024-10-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_country_alter_feedback_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
