# Generated by Django 5.1.4 on 2024-12-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
    ]
